### ISSUE TITLE
Share available TUG slides?

### ISSUE THREAD

**Issue by amklinv** [trilinos/trilinos.github.io#15]
Please consider this a feature request rather than a bug.  The newest TUG tutorial slides I was able to find online were from 2014.  Would it be possible to post newer TUG slides on the website?

**Comment by maherou** [comment]
2014 may be the last year we recorded talks.  I know for at least the last couple of years, we did not record them.

On Apr 1, 2019, at 11:22 AM, Alicia Klinvex <notifications@github.com<mailto:notifications@github.com>> wrote:


Please consider this a feature request rather than a bug. The newest TUG tutorial slides I was able to find online were from 2014. Would it be possible to post newer TUG slides on the website?

**Comment by mhoemmen** [comment]
I have some newer TUG tutorial slides.  It's not a single tutorial, though -- we had split them up into multiple slide decks.  Would that be OK?

**Comment by maherou** [comment]
Good idea, Mark.  We can certainly collect the slides from previous meetings, even if there are not recordings.

BTW, trilinos.github.io<http://trilinos.github.io> is a GitHub repo, so anyone can commit or (if more comfortable) submit a pull request.

Thanks.

Mike

On Apr 1, 2019, at 11:42 AM, Mark Hoemmen <notifications@github.com<mailto:notifications@github.com>> wrote:


I have some newer TUG tutorial slides. It's not a single tutorial, though -- we had split them up into multiple slide decks. Would that be OK?

**Comment by maherou** [comment]
@jwillenbring: Do you have TUG slides that we can post?

**Comment by ccober6** [comment]
For the past several years, we have been posting slides and videos of TUG presentations.  Closing as complete.
