### ISSUE TITLE
What is the plan for this trilinos.github.io site?

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/trilinos.github.io#2]
Seems like it would be a **lot** of work to replace the current trilinos.org WordPress site.  Is this just an experimentation or is there a real plan to make this transition?  And if so, what is the timeline plan for that?

**Comment by maherou** [comment]
trilinos.github.io has become the de facto portal for Trilinos.  Doxygen documentation is still maintained on the trilinos.org, but pointers to this documentation are integrated into trilinos.github.io.  Presently, we are working on removing incorrect and stale information from trilinos.github.io.  We are also encouraging the user community to contribute in this effort.  Contributions are easier in the GitHub environment because the website is just another repo.

**Comment by bartlettroscoe** [comment]
@maherou, note that the link to the trilinos configure documentation is still broken on the new site from:

* https://trilinos.github.io/documentation.html

Try clicking on the links in the second bullet "Trilinos CMake Reference".

**Comment by maherou** [comment]
Do you know where this file exists?

**Comment by maherou** [comment]
The PDF version of TrilinosBuildReference.pdf is present as pointed to, but I cannot find the file TrilinosBuildReference.html

**Comment by bartlettroscoe** [comment]
> Do you know where this file exists?

It lives in Trilinos under Trilinos/doc/build_ref/

> The PDF version of TrilinosBuildReference.pdf is present as pointed to, but I cannot find the file TrilinosBuildReference.html

Okay, PDF is better than nothing but not as nice as the HTML version.
