### ISSUE TITLE
TUG 2017 page in trilinos.github.io

### ISSUE THREAD

**Issue by duongdo27** [trilinos/trilinos.github.io#9]
Hi @maherou @jwillenbring,

I notice that two of you make some changes for the TUG 2017 page. Do you want me to make any changes for the webpage, such as the logo because I see that you try to update the logo multiple times.

**Comment by maherou** [comment]
Adding the new logo would be nice.  I was trying to get it to work while attending a meeting and had to quit.

Thanks.

DH

On Oct 19, 2017, at 7:41 PM, duongdo27 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @maherou<https://github.com/maherou> @jwillenbring<https://github.com/jwillenbring>,

I notice that two of you make some changes for the TUG 2017 page. Do you want me to make any changes for the webpage, such as the logo because I see that you try to update the logo multiple times.

-

**Comment by duongdo27** [comment]
@maherou New logo is added to [https://trilinos.github.io/](https://trilinos.github.io/)

**Comment by maherou** [comment]
Closing as done.
